[package]
name = "actix-scaffolding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-web = "4.4.1"
chrono = "0.4.33"
diesel = {version = "2.1.4", features = ["postgres","r2d2","chrono","numeric"]}
dotenv = "0.15.0"
sailfish = { version = "0.8.3", features = ["serde","serde_json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
